default_settings:
  max-volume: "130"
  show-video: "no"
  show-lyrics: "yes"
  authenticated: "yes"
  auto-recommendations: "yes"
  recommendation-count: "3"
  keyboard-shortcuts:
    end-song: "q"
    pause: "p"
    translate-lyrics: "t"
  backup:
    enabled: "yes"
    auto-backup: "yes"
    backup-frequency: "7" # Days between automatic backups
    backup-location: "default" # "default" or custom path
    backup-items:
      history: "yes"
      playlists: "yes"
      settings: "yes"
      cache: "no" # Cache can be large, off by default
    manual-backup:
      status: "off"
      timed:
        status: "off"
        daily: "off"
        weekly: "off"
        monthly: "off"
