default_settings:
  max-volume: "130"
  show-video: "no"
  show-lyrics: "yes"
  authenticated: "yes"
  keyboard-shortcuts:
    end-song: "q"
    pause: "p"
    translate-lyrics: "t"
  backup:
    auto-backup: "on"
    manual-backup:
      status: "off"
      timed:
        status: "off"
        daily: "off"
        weekly: "off"
        monthly: "off"
